name: Docker Hub Build

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      # setup dependencies for multiple platform builds
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # setup Docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build local version to use for testing
      - name: Build local image for testing
        run: |
          docker build . -t k8v

      # create a Kubernetes cluster in Docker to use for testing
      - name: Setup Kubernetes in Docker cluster
        uses: helm/kind-action@v1.2.0        

      # create all resources we need for testing the tool 
      - name: Create test resources from manifests
        run: |
          echo "current-context:" $(kubectl config current-context)
          kubectl cluster-info

          kubectl create -f tests/manifests
          kubectl wait --for=condition=Ready pod -l app --timeout=60s

          kubectl get svc -owide
          kubectl get deploy -owide
          kubectl get pods -owide

      # execute the pytests
      - name: Run tests using Docker container
        shell: 'script --return --quiet --command "bash {0}"'
        run: |
          docker run --rm -it --network="host" -v ~/.kube:/root/.kube --entrypoint=sh k8v -c "cat /root/.kube/config"
          docker run --rm -it --network="host" -v ~/.kube:/root/.kube k8v -R -t -A
          docker run --rm -it --network="host" -v ~/.kube:/root/.kube --entrypoint=/app/bin/run_tests k8v

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # login to the official Docker Hub      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # push the Docker image to the official Docker Hub
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jasonhanks/k8v:latest
